name: Bot Runner

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - name: Running Bot
        run: |
          pip install -r requirements.txt
          python main.py
